# Generated by Django 4.0.1 on 2022-01-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
                ('img', models.ImageField(upload_to='Images')),
                ('intern_status', models.BooleanField(default=False)),
            ],
        ),
    ]
